USE [master]
GO
/****** Object:  Database [000B-CONTROL]    Script Date: 19/07/2023 6:49:13 AM ******/
CREATE DATABASE [000B-CONTROL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'000B-CONTROL', FILENAME = N'D:\softwareInstalled\Microsoft SQL Server\MSSQL15.SQL01\MSSQL\DATA\000B-CONTROL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'000B-CONTROL_log', FILENAME = N'D:\softwareInstalled\Microsoft SQL Server\MSSQL15.SQL01\MSSQL\DATA\000B-CONTROL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [000B-CONTROL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [000B-CONTROL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [000B-CONTROL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [000B-CONTROL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [000B-CONTROL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [000B-CONTROL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [000B-CONTROL] SET ARITHABORT OFF 
GO
ALTER DATABASE [000B-CONTROL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [000B-CONTROL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [000B-CONTROL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [000B-CONTROL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [000B-CONTROL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [000B-CONTROL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [000B-CONTROL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [000B-CONTROL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [000B-CONTROL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [000B-CONTROL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [000B-CONTROL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [000B-CONTROL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [000B-CONTROL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [000B-CONTROL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [000B-CONTROL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [000B-CONTROL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [000B-CONTROL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [000B-CONTROL] SET RECOVERY FULL 
GO
ALTER DATABASE [000B-CONTROL] SET  MULTI_USER 
GO
ALTER DATABASE [000B-CONTROL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [000B-CONTROL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [000B-CONTROL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [000B-CONTROL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [000B-CONTROL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [000B-CONTROL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'000B-CONTROL', N'ON'
GO
ALTER DATABASE [000B-CONTROL] SET QUERY_STORE = OFF
GO
USE [000B-CONTROL]
GO
/****** Object:  Table [dbo].[Empresa]    Script Date: 19/07/2023 6:49:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empresa](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[baseDatos] [varchar](50) NOT NULL,
	[cedula] [varchar](50) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[correo] [varchar](50) NOT NULL,
	[telefonoUno] [varchar](50) NOT NULL,
	[telefonoDos] [varchar](50) NOT NULL,
	[paginaWeb] [varchar](50) NOT NULL,
	[direccion] [varchar](50) NOT NULL,
	[repNombre] [varchar](50) NOT NULL,
	[repCedula] [varchar](50) NOT NULL,
	[repTelefono] [varchar](50) NOT NULL,
	[repCorreo] [varchar](50) NOT NULL,
	[estado] [tinyint] NOT NULL,
 CONSTRAINT [PK_Empresa] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 19/07/2023 6:49:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[correo] [varchar](50) NOT NULL,
	[contrasena] [varchar](50) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[direccion] [varchar](100) NOT NULL,
	[telefono] [varchar](50) NOT NULL,
	[estado] [tinyint] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Usuario__D745C2F85E2B0F06] UNIQUE NONCLUSTERED 
(
	[correo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsuarioEmpresa]    Script Date: 19/07/2023 6:49:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioEmpresa](
	[usuarioId] [int] NOT NULL,
	[empresaId] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UsuarioEmpresa]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioEmpresa_Empresa] FOREIGN KEY([empresaId])
REFERENCES [dbo].[Empresa] ([id])
GO
ALTER TABLE [dbo].[UsuarioEmpresa] CHECK CONSTRAINT [FK_UsuarioEmpresa_Empresa]
GO
ALTER TABLE [dbo].[UsuarioEmpresa]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioEmpresa_Usuario] FOREIGN KEY([usuarioId])
REFERENCES [dbo].[Usuario] ([id])
GO
ALTER TABLE [dbo].[UsuarioEmpresa] CHECK CONSTRAINT [FK_UsuarioEmpresa_Usuario]
GO
/****** Object:  StoredProcedure [dbo].[SPCrearEmpresa]    Script Date: 19/07/2023 6:49:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPCrearEmpresa]
	-- Add the parameters for the stored procedure here
	@id INT, 
	@cedula VARCHAR(50)

AS
BEGIN	
	SET NOCOUNT ON;

   
   DECLARE 
		@SQL nvarchar(MAX), 
		@newId VARCHAR(5),
		@newName VARCHAR(150), 
		@newNameLog VARCHAR(150),
		@myInt INT;
   
   SET @newId = (SELECT RIGHT(REPLICATE('0', 3) + CAST(@id AS VARCHAR(3)), 3));
   SET @newName =  UPPER(@newId + 'B-' + @cedula)
   SET @newNameLog = UPPER(@newName + '_log')
	
	-- Contexto
	SET @SQL = N'USE [master]'
	EXEC sp_executesql @SQL;

	-- Crear la base de datos
	SET @SQL = N'CREATE DATABASE ' + QUOTENAME(@newName);
	EXEC sp_executesql @SQL;

	SELECT @newName AS nombre

END

--exec [dbo].[SPCrearEmpresa] 1,'008B-45545646554'
GO
USE [master]
GO
ALTER DATABASE [000B-CONTROL] SET  READ_WRITE 
GO
